name: Build and upload package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --release
      
    - name: Copy artifact
      run: mkdir -p release && cp target/release/id_by_ringtone release/

    - uses: actions/upload-artifact@v1
      with:
        name: id_by_ringtone_${{ github.sha }}_amd64
        path: release
